import { db, jobRolesTable, leaveTypesTable, workersTable } from "@workspace/db";

async function seed() {
  // Seed job roles
  const jobs = [
    {
      title: "Senior Infrastructure Engineer",
      department: "Engineering & Technology",
      description: "Lead the design and implementation of large-scale infrastructure projects across Asia and Africa. You will oversee engineering teams, manage subcontractors, and ensure projects are delivered on time and within budget.",
      responsibilities: "• Lead engineering design teams on infrastructure projects\n• Manage project timelines and budgets ($5M–$50M range)\n• Coordinate with international subcontractors and local partners\n• Ensure compliance with local regulations and SinoGlobal standards\n• Prepare progress reports for senior leadership",
      requirements: "• Bachelor's or Master's in Civil/Structural Engineering\n• 8+ years of large-scale infrastructure experience\n• PMP certification preferred\n• Experience working in developing markets (Africa, Southeast Asia)\n• Mandarin proficiency is an advantage",
      salary: "$95,000 – $140,000/year + housing allowance",
      photoUrl: "https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=200&h=200&fit=crop",
      isActive: true,
    },
    {
      title: "International Finance Manager",
      department: "Finance & Investment",
      description: "Manage financial operations and reporting across multiple international subsidiaries. This role involves strategic budgeting, treasury management, and financial risk analysis for SinoGlobal's global portfolio.",
      responsibilities: "• Consolidate financial statements from 10+ subsidiaries\n• Manage FX exposure and treasury operations\n• Lead annual budgeting and quarterly forecasting\n• Prepare board-level financial presentations\n• Liaise with external auditors and regulatory bodies",
      requirements: "• CPA, CFA, or ACCA qualified\n• 7+ years in multinational finance\n• Experience with SAP or Oracle ERP\n• Strong knowledge of IFRS\n• Excellent Mandarin and English communication",
      salary: "$85,000 – $125,000/year + performance bonus",
      photoUrl: "https://images.unsplash.com/photo-1554224155-6726b3ff858f?w=200&h=200&fit=crop",
      isActive: true,
    },
    {
      title: "Operations Director — West Africa",
      department: "Operations & Logistics",
      description: "Oversee all operational activities in SinoGlobal's West Africa region (Nigeria, Ghana, Senegal, Côte d'Ivoire). Manage a team of 200+ staff and drive the region's revenue growth and operational efficiency.",
      responsibilities: "• P&L responsibility for West Africa region ($120M annual revenue)\n• Manage relationships with government bodies and local partners\n• Drive operational efficiency and quality standards\n• Lead talent acquisition and development in the region\n• Represent SinoGlobal in stakeholder meetings and industry forums",
      requirements: "• 12+ years of senior operations experience\n• Proven P&L management at regional level\n• Experience in West Africa mandatory\n• MBA or equivalent postgraduate qualification\n• French language skills are a strong advantage",
      salary: "$150,000 – $200,000/year + expat package",
      photoUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&h=200&fit=crop",
      isActive: true,
    },
    {
      title: "Legal & Compliance Counsel",
      department: "Legal & Compliance",
      description: "Provide comprehensive legal support for SinoGlobal's international contracts, joint ventures, and regulatory compliance. Advise senior management on legal risk and corporate governance matters.",
      responsibilities: "• Draft and review international commercial contracts\n• Advise on M&A transactions and joint ventures\n• Ensure compliance with multi-jurisdictional regulations\n• Manage litigation and dispute resolution\n• Develop internal compliance training programs",
      requirements: "• LLB/JD from accredited university\n• Bar admission in at least one common law jurisdiction\n• 6+ years in corporate or international commercial law\n• Cross-border transaction experience\n• Bilingual English/Mandarin strongly preferred",
      salary: "$90,000 – $130,000/year",
      photoUrl: "https://images.unsplash.com/photo-1589829085413-56de8ae18c73?w=200&h=200&fit=crop",
      isActive: true,
    },
    {
      title: "Senior Software Engineer (Cloud Platform)",
      department: "Information Technology",
      description: "Join the Cloud Platform team to build scalable, resilient enterprise software products used by SinoGlobal's subsidiaries and clients across 43 countries. Work with cutting-edge cloud technologies and distributed systems.",
      responsibilities: "• Design and build microservices for enterprise cloud platform\n• Optimize system performance and reliability (99.99% SLA)\n• Mentor junior engineers and contribute to technical roadmap\n• Collaborate with product managers and international stakeholders\n• Participate in on-call rotation for critical systems",
      requirements: "• 6+ years of software engineering experience\n• Proficiency in TypeScript, Go, or Python\n• Experience with Kubernetes, AWS or GCP\n• Distributed systems and microservices architecture\n• Excellent problem-solving skills",
      salary: "$100,000 – $150,000/year + equity",
      photoUrl: "https://images.unsplash.com/photo-1516116216624-53e697fedbea?w=200&h=200&fit=crop",
      isActive: true,
    },
    {
      title: "Clinical Research Scientist",
      department: "Healthcare & Pharmaceuticals",
      description: "Lead clinical research initiatives within BioSino Medical, SinoGlobal's pharmaceutical division. Design and manage Phase II/III clinical trials for novel drug candidates in partnership with hospitals across China, Southeast Asia, and Africa.",
      responsibilities: "• Design and execute clinical trial protocols (Phase II/III)\n• Analyze trial data and prepare regulatory submissions\n• Collaborate with CROs and hospital partners across 3 continents\n• Ensure GCP compliance throughout all research activities\n• Present findings at international scientific conferences",
      requirements: "• PhD in Pharmacology, Medicine, or related life science\n• 4+ years post-doctoral clinical research experience\n• Proven GCP and ICH guideline knowledge\n• Experience with FDA/EMA/NMPA regulatory submissions\n• Published research in peer-reviewed journals",
      salary: "$80,000 – $115,000/year",
      photoUrl: "https://images.unsplash.com/photo-1579154204601-01588f351e67?w=200&h=200&fit=crop",
      isActive: true,
    },
  ];

  for (const job of jobs) {
    await db.insert(jobRolesTable).values(job).onConflictDoNothing();
  }
  console.log(`Seeded ${jobs.length} job roles`);

  // Seed leave types
  const leaveTypes = [
    {
      name: "Annual Leave",
      description: "Standard paid annual leave for rest and recreation. Available to all permanent employees after completing 6 months of service.",
      maxDays: 21,
      amount: 0,
      requiresApproval: true,
      isActive: true,
    },
    {
      name: "Medical / Sick Leave",
      description: "Paid leave due to illness or injury requiring medical attention. A valid medical certificate is required for absences exceeding 3 consecutive days.",
      maxDays: 30,
      amount: 0,
      requiresApproval: false,
      isActive: true,
    },
    {
      name: "Family Emergency Leave",
      description: "Emergency leave for urgent family matters including hospitalization of immediate family members, death of a family member, or other family crises.",
      maxDays: 7,
      amount: 500,
      requiresApproval: true,
      isActive: true,
    },
    {
      name: "Maternity / Paternity Leave",
      description: "Paid parental leave for the birth or legal adoption of a child. Maternity: 16 weeks. Paternity: 2 weeks.",
      maxDays: 112,
      amount: 0,
      requiresApproval: true,
      isActive: true,
    },
    {
      name: "Study / Examination Leave",
      description: "Paid leave for approved professional development examinations directly related to the employee's current or development role at SinoGlobal.",
      maxDays: 10,
      amount: 200,
      requiresApproval: true,
      isActive: true,
    },
    {
      name: "Home Country Vacation",
      description: "Special paid leave for internationally-posted employees to travel to their home country. Includes a travel allowance to cover return airfare.",
      maxDays: 14,
      amount: 2500,
      requiresApproval: true,
      isActive: true,
    },
  ];

  for (const lt of leaveTypes) {
    await db.insert(leaveTypesTable).values(lt).onConflictDoNothing();
  }
  console.log(`Seeded ${leaveTypes.length} leave types`);

  // Seed workers
  const workers = [
    {
      firstName: "James",
      lastName: "Okafor",
      email: "j.okafor@sinoglobal.com",
      phone: "+234 801 234 5678",
      accessToken: "SGE-JAMES-OKAFR",
      jobTitle: "Operations Director — West Africa",
      department: "Operations & Logistics",
      contractStart: "2022-03-01",
      contractEnd: "2025-02-28",
      contractDeal: "3-year contract with annual performance review and expat package",
      paymentStatus: "paid",
      paymentAmount: "175000.00",
      paymentPaid: "175000.00",
      assignedCountry: "Nigeria",
      countryEntryDate: "2022-03-05",
      countryStayYears: 3,
      photoUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&h=200&fit=crop",
      nationality: "Nigerian",
      passportNumber: "A12345678",
      status: "active",
      hiredBy: "thompsonbaro@gmail.com",
      notes: "Senior regional lead, exceptional performance in Q1 2024.",
    },
    {
      firstName: "Li",
      lastName: "Wei",
      email: "l.wei@sinoglobal.com",
      phone: "+86 138 0000 1111",
      accessToken: "SGE-LIWEI-00001",
      jobTitle: "Senior Infrastructure Engineer",
      department: "Engineering & Technology",
      contractStart: "2021-07-15",
      contractEnd: "2024-07-14",
      contractDeal: "3-year contract with housing allowance and repatriation benefit",
      paymentStatus: "paid",
      paymentAmount: "120000.00",
      paymentPaid: "120000.00",
      assignedCountry: "Kenya",
      countryEntryDate: "2021-08-01",
      countryStayYears: 3,
      photoUrl: "https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=200&h=200&fit=crop",
      nationality: "Chinese",
      passportNumber: "G87654321",
      status: "active",
      hiredBy: "thompsonbaro@gmail.com",
      notes: "Led the Mombasa port expansion phase 2 project.",
    },
    {
      firstName: "Amara",
      lastName: "Diallo",
      email: "a.diallo@sinoglobal.com",
      phone: "+221 77 456 7890",
      accessToken: "SGE-AMARA-DIALL",
      jobTitle: "International Finance Manager",
      department: "Finance & Investment",
      contractStart: "2023-01-10",
      contractEnd: "2026-01-09",
      contractDeal: "3-year contract with performance bonus structure",
      paymentStatus: "pending",
      paymentAmount: "105000.00",
      paymentPaid: "52500.00",
      assignedCountry: "Senegal",
      countryEntryDate: "2023-01-15",
      countryStayYears: 3,
      photoUrl: "https://images.unsplash.com/photo-1554224155-6726b3ff858f?w=200&h=200&fit=crop",
      nationality: "Senegalese",
      passportNumber: "SN9876543",
      status: "active",
      hiredBy: "thompsonbaro@gmail.com",
      notes: "Managing treasury for West Africa francophone subsidiaries.",
    },
    {
      firstName: "Sofia",
      lastName: "Martínez",
      email: "s.martinez@sinoglobal.com",
      phone: "+34 612 345 678",
      accessToken: "SGE-SOFIA-MARTZ",
      jobTitle: "Legal & Compliance Counsel",
      department: "Legal & Compliance",
      contractStart: "2020-09-01",
      contractEnd: "2024-08-31",
      contractDeal: "4-year contract with annual review; remote-eligible",
      paymentStatus: "paid",
      paymentAmount: "115000.00",
      paymentPaid: "115000.00",
      assignedCountry: "Spain",
      countryEntryDate: "2020-09-01",
      countryStayYears: 4,
      photoUrl: "https://images.unsplash.com/photo-1589829085413-56de8ae18c73?w=200&h=200&fit=crop",
      nationality: "Spanish",
      passportNumber: "XDA123456",
      status: "active",
      hiredBy: "thompsonbaro@gmail.com",
      notes: "Specializes in EU regulatory compliance and cross-border M&A.",
    },
    {
      firstName: "David",
      lastName: "Mensah",
      email: "d.mensah@sinoglobal.com",
      phone: "+233 244 789 012",
      accessToken: "SGE-DAVID-MENSH",
      jobTitle: "Senior Software Engineer (Cloud Platform)",
      department: "Information Technology",
      contractStart: "2023-06-01",
      contractEnd: "2026-05-31",
      contractDeal: "3-year contract with equity participation and remote-work allowance",
      paymentStatus: "paid",
      paymentAmount: "130000.00",
      paymentPaid: "130000.00",
      assignedCountry: "Ghana",
      countryEntryDate: "2023-06-05",
      countryStayYears: 3,
      photoUrl: "https://images.unsplash.com/photo-1516116216624-53e697fedbea?w=200&h=200&fit=crop",
      nationality: "Ghanaian",
      passportNumber: "GH5432109",
      status: "active",
      hiredBy: "thompsonbaro@gmail.com",
      notes: "Core contributor to the SGE cloud infrastructure migration project.",
    },
    {
      firstName: "Mei",
      lastName: "Chen",
      email: "m.chen@sinoglobal.com",
      phone: "+86 139 8765 4321",
      accessToken: "SGE-MEICH-00002",
      jobTitle: "Clinical Research Scientist",
      department: "Healthcare & Pharmaceuticals",
      contractStart: "2022-11-01",
      contractEnd: "2025-10-31",
      contractDeal: "3-year contract with laboratory equipment allowance",
      paymentStatus: "overdue",
      paymentAmount: "95000.00",
      paymentPaid: "47500.00",
      assignedCountry: "China",
      countryEntryDate: "2022-11-01",
      countryStayYears: 3,
      photoUrl: "https://images.unsplash.com/photo-1579154204601-01588f351e67?w=200&h=200&fit=crop",
      nationality: "Chinese",
      passportNumber: "E11223344",
      status: "active",
      hiredBy: "thompsonbaro@gmail.com",
      notes: "Lead researcher on Phase III malaria vaccine trial in partnership with WHO.",
    },
  ];

  for (const worker of workers) {
    await db.insert(workersTable).values(worker).onConflictDoNothing();
  }
  console.log(`Seeded ${workers.length} workers`);

  console.log("Seed complete!");
  process.exit(0);
}

seed().catch((err) => { console.error(err); process.exit(1); });
